artifact_root: artifact
data_root: data

data_ingestion:
    root_dir: data/raw
    cloud_train_data_path: "data/raw/train.csv"
    cloud_test_data_path: "data/raw/test.csv"
    bucket_name: "ai_text_guard_bucket"
    local_data_dir: data/raw
    local_train_path: data/raw/train.csv
    local_test_path: data/raw/test.csv
  
data_validation:
    root_dir: artifact/data_validation
    validated_data_report_file_path: artifact/data_validation/data_validation_report.txt
    
data_transformation:
    artifact_root_dir: artifact/data_transformation
    data_root_dir: data/transformed
    transformed_train_data_path: data/transformed/train.npy
    transformed_test_data_path: data/transformed/test.npy
    transformed_val_data_path: data/transformed/val.npy
    temp_model_dir: temp
    data_transformation_object_path: artifact/data_transformation/text_features_preprocessor.pkl
    test_split_size: 0.2

model_trainer:
    root_dir: artifact/model_trainer
    lr_level_1_path: artifact/model_trainer/lr_level1.pkl
    xgb_level_1_path: artifact/model_trainer/xgb_level1.pkl
    meta_lr_path: artifact/model_trainer/meta_lr.pkl
    enable_tuning: true
    final_model_path: artifact/model_trainer/stacked_model.pkl

    lr_level1_oof_predictions_path: artifact/model_trainer/level1_oof/lr_oof.npy
    xgb_level1_oof_predictions_path: artifact/model_trainer/level1_oof/xgb_oof.npy

    folds: 5
    tuning:
        level1:
            lr:
                C: {type: float, low: 0.001, high: 10.0, log: true}
                penalty: ["l1", "l2"]
                solver: ["liblinear", "saga"]
                max_iter: {type: int, low: 300, high: 1000}

            xgb:
                n_estimators: {type: int, low: 100, high: 700}
                max_depth: {type: int, low: 3, high: 8}
                learning_rate: {type: float, low: 0.005, high: 0.1, log: true}
                subsample: [0.6, 0.7, 0.8, 1.0]
                colsample_bytree: [0.5, 0.7, 0.8, 1.0]
                min_child_weight: {type: int, low: 1, high: 7}
                gamma: {type: float, low: 0.001, high: 0.5}
                reg_alpha: {type: float, low: 0.001, high: 1.0, log: true}
                reg_lambda: {type: float, low: 0.1, high: 5.0, log: true}


        level2:

            lr:
                C: {type: float, low: 0.001, high: 10.0, log: true}
                penalty: ["l2"]
                solver: ["saga", "liblinear"]
                max_iter: {type: int, low: 300, high: 1000}

prediction:
    final_model_path: artifact/model_trainer/stacked_model.pkl
