name: Build & Push Docker Images (Docker Hub)

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

# --- 1. AUTHENTICATE WITH GOOGLE CLOUD ---
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        # ADD THIS LINE: It forces the action to create a file on the runner
        create_credentials_file: true

    # --- 2. DOWNLOAD MODEL ---
    - name: 'Download Model'
      run: |
        # Force gsutil to use the file created in the step above
        export GOOGLE_APPLICATION_CREDENTIALS="${{ steps.auth.outputs.credentials_file_path }}"
        
        # Verify it works
        gcloud auth list
        
        mkdir -p model
        gsutil cp gs://ai_text_guard_bucket/model/stacked_model.pkl ./model/
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # --- 3. BUILD & PUSH BACKEND (With Model) ---
    - name: Build & push backend image
      uses: docker/build-push-action@v6
      with:
        context: .
        
        file: Docker/Dockerfile.backend_dockerhub 
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aichettextguard-backend:latest

    # --- 4. BUILD & PUSH UI ---
    - name: Build & push UI image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Docker/Dockerfile.ui_dockerhub 
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aichettextguard-ui:latest