name: Build & Push Docker Images (Docker Hub)

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

# --- 1. AUTHENTICATE WITH GOOGLE CLOUD ---
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        create_credentials_file: true

    # --- 2. DOWNLOAD MODEL ---
    - name: 'Download Model'
      run: |
        # 1. Manually activate the service account using the file created in step 1
        gcloud auth activate-service-account --key-file="${{ steps.auth.outputs.credentials_file_path }}"
        
        # 2. Set the project explicitly (it helps gsutil find the right path)
        gcloud config set project ${{ steps.auth.outputs.project_id }}
        
        # 3. Now verify - this should NO LONGER say "No credentialed accounts"
        gcloud auth list
        
        # 4. Perform the copy
        mkdir -p model
        gsutil cp gs://ai_text_guard_bucket/model/stacked_model.pkl ./model/





    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # --- 3. BUILD & PUSH BACKEND (With Model) ---
    - name: Build & push backend image
      uses: docker/build-push-action@v6
      with:
        context: .
        
        file: Docker/Dockerfile.backend_dockerhub 
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aichettextguard-backend:latest

    # --- 4. BUILD & PUSH UI ---
    - name: Build & push UI image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Docker/Dockerfile.ui_dockerhub 
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/aichettextguard-ui:latest